import { ICountry } from './../../interfaces/country';
export const countries = [
  {
    name: 'Åland Islands',
    topLevelDomain: ['.ax'],
    alpha2Code: 'AX',
    alpha3Code: 'ALA',
    callingCodes: ['358'],
    capital: 'Mariehamn',
    altSpellings: ['AX', 'Aaland', 'Aland', 'Ahvenanmaa'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 28875,
    latlng: [60.116667, 19.9],
    demonym: 'Ålandish',
    area: 1580,
    timezones: ['UTC+02:00'],
    nativeName: 'Åland',
    numericCode: '248',
    flags: {
      svg: 'https://flagcdn.com/ax.svg',
      png: 'https://flagcdn.com/w320/ax.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'sv',
        iso639_2: 'swe',
        name: 'Swedish',
        nativeName: 'svenska',
      },
    ],
    translations: {
      br: 'Åland',
      pt: 'Ilhas de Aland',
      nl: 'Ålandeilanden',
      hr: 'Ålandski otoci',
      fa: 'جزایر الند',
      de: 'Åland',
      es: 'Alandia',
      fr: 'Åland',
      ja: 'オーランド諸島',
      it: 'Isole Aland',
      hu: 'Åland-szigetek',
    },
    flag: 'https://flagcdn.com/ax.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    independent: false,
  },
  {
    name: 'Albania',
    topLevelDomain: ['.al'],
    alpha2Code: 'AL',
    alpha3Code: 'ALB',
    callingCodes: ['355'],
    capital: 'Tirana',
    altSpellings: ['AL', 'Shqipëri', 'Shqipëria', 'Shqipnia'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 2837743,
    latlng: [41, 20],
    demonym: 'Albanian',
    area: 28748,
    gini: 33.2,
    timezones: ['UTC+01:00'],
    borders: ['MNE', 'GRC', 'MKD', 'UNK'],
    nativeName: 'Shqipëria',
    numericCode: '008',
    flags: {
      svg: 'https://flagcdn.com/al.svg',
      png: 'https://flagcdn.com/w320/al.png',
    },
    currencies: [
      {
        code: 'ALL',
        name: 'Albanian lek',
        symbol: 'L',
      },
    ],
    languages: [
      {
        iso639_1: 'sq',
        iso639_2: 'sqi',
        name: 'Albanian',
        nativeName: 'Shqip',
      },
    ],
    translations: {
      br: 'Albania',
      pt: 'Albânia',
      nl: 'Albanië',
      hr: 'Albanija',
      fa: 'آلبانی',
      de: 'Albanien',
      es: 'Albania',
      fr: 'Albanie',
      ja: 'アルバニア',
      it: 'Albania',
      hu: 'Albánia',
    },
    flag: 'https://flagcdn.com/al.svg',
    regionalBlocs: [
      {
        acronym: 'CEFTA',
        name: 'Central European Free Trade Agreement',
      },
    ],
    cioc: 'ALB',
    independent: true,
  },
  {
    name: 'Andorra',
    topLevelDomain: ['.ad'],
    alpha2Code: 'AD',
    alpha3Code: 'AND',
    callingCodes: ['376'],
    capital: 'Andorra la Vella',
    altSpellings: ['AD', 'Principality of Andorra', "Principat d'Andorra"],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 77265,
    latlng: [42.5, 1.5],
    demonym: 'Andorran',
    area: 468,
    timezones: ['UTC+01:00'],
    borders: ['FRA', 'ESP'],
    nativeName: 'Andorra',
    numericCode: '020',
    flags: {
      svg: 'https://flagcdn.com/ad.svg',
      png: 'https://flagcdn.com/w320/ad.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'ca',
        iso639_2: 'cat',
        name: 'Catalan',
        nativeName: 'català',
      },
    ],
    translations: {
      br: 'Andorra',
      pt: 'Andorra',
      nl: 'Andorra',
      hr: 'Andora',
      fa: 'آندورا',
      de: 'Andorra',
      es: 'Andorra',
      fr: 'Andorre',
      ja: 'アンドラ',
      it: 'Andorra',
      hu: 'Andorra',
    },
    flag: 'https://flagcdn.com/ad.svg',
    cioc: 'AND',
    independent: true,
  },
  {
    name: 'Austria',
    topLevelDomain: ['.at'],
    alpha2Code: 'AT',
    alpha3Code: 'AUT',
    callingCodes: ['43'],
    capital: 'Vienna',
    altSpellings: ['AT', 'Österreich', 'Osterreich', 'Oesterreich'],
    subregion: 'Central Europe',
    region: 'Europe',
    population: 8917205,
    latlng: [47.33333333, 13.33333333],
    demonym: 'Austrian',
    area: 83871,
    gini: 30.8,
    timezones: ['UTC+01:00'],
    borders: ['CZE', 'DEU', 'HUN', 'ITA', 'LIE', 'SVK', 'SVN', 'CHE'],
    nativeName: 'Österreich',
    numericCode: '040',
    flags: {
      svg: 'https://flagcdn.com/at.svg',
      png: 'https://flagcdn.com/w320/at.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'de',
        iso639_2: 'deu',
        name: 'German',
        nativeName: 'Deutsch',
      },
    ],
    translations: {
      br: 'Aostria',
      pt: 'Áustria',
      nl: 'Oostenrijk',
      hr: 'Austrija',
      fa: 'اتریش',
      de: 'Österreich',
      es: 'Austria',
      fr: 'Autriche',
      ja: 'オーストリア',
      it: 'Austria',
      hu: 'Ausztria',
    },
    flag: 'https://flagcdn.com/at.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'AUT',
    independent: true,
  },
  {
    name: 'Belarus',
    topLevelDomain: ['.by'],
    alpha2Code: 'BY',
    alpha3Code: 'BLR',
    callingCodes: ['375'],
    capital: 'Minsk',
    altSpellings: [
      'BY',
      'Bielaruś',
      'Republic of Belarus',
      'Белоруссия',
      'Республика Беларусь',
      'Belorussiya',
      'Respublika Belarus’',
    ],
    subregion: 'Eastern Europe',
    region: 'Europe',
    population: 9398861,
    latlng: [53, 28],
    demonym: 'Belarusian',
    area: 207600,
    gini: 25.3,
    timezones: ['UTC+03:00'],
    borders: ['LVA', 'LTU', 'POL', 'RUS', 'UKR'],
    nativeName: 'Белару́сь',
    numericCode: '112',
    flags: {
      svg: 'https://flagcdn.com/by.svg',
      png: 'https://flagcdn.com/w320/by.png',
    },
    currencies: [
      {
        code: 'BYN',
        name: 'New Belarusian ruble',
        symbol: 'Br',
      },
      {
        code: 'BYR',
        name: 'Old Belarusian ruble',
        symbol: 'Br',
      },
    ],
    languages: [
      {
        iso639_1: 'be',
        iso639_2: 'bel',
        name: 'Belarusian',
        nativeName: 'беларуская мова',
      },
      {
        iso639_1: 'ru',
        iso639_2: 'rus',
        name: 'Russian',
        nativeName: 'Русский',
      },
    ],
    translations: {
      br: 'Belarus',
      pt: 'Bielorrússia',
      nl: 'Wit-Rusland',
      hr: 'Bjelorusija',
      fa: 'بلاروس',
      de: 'Weißrussland',
      es: 'Bielorrusia',
      fr: 'Biélorussie',
      ja: 'ベラルーシ',
      it: 'Bielorussia',
      hu: 'Fehéroroszország',
    },
    flag: 'https://flagcdn.com/by.svg',
    regionalBlocs: [
      {
        acronym: 'EEU',
        name: 'Eurasian Economic Union',
        otherAcronyms: ['EAEU'],
      },
    ],
    cioc: 'BLR',
    independent: true,
  },
  {
    name: 'Belgium',
    topLevelDomain: ['.be'],
    alpha2Code: 'BE',
    alpha3Code: 'BEL',
    callingCodes: ['32'],
    capital: 'Brussels',
    altSpellings: [
      'BE',
      'België',
      'Belgie',
      'Belgien',
      'Belgique',
      'Kingdom of Belgium',
      'Koninkrijk België',
      'Royaume de Belgique',
      'Königreich Belgien',
    ],
    subregion: 'Western Europe',
    region: 'Europe',
    population: 11555997,
    latlng: [50.83333333, 4],
    demonym: 'Belgian',
    area: 30528,
    gini: 27.2,
    timezones: ['UTC+01:00'],
    borders: ['FRA', 'DEU', 'LUX', 'NLD'],
    nativeName: 'België',
    numericCode: '056',
    flags: {
      svg: 'https://flagcdn.com/be.svg',
      png: 'https://flagcdn.com/w320/be.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'nl',
        iso639_2: 'nld',
        name: 'Dutch',
        nativeName: 'Nederlands',
      },
      {
        iso639_1: 'fr',
        iso639_2: 'fra',
        name: 'French',
        nativeName: 'français',
      },
      {
        iso639_1: 'de',
        iso639_2: 'deu',
        name: 'German',
        nativeName: 'Deutsch',
      },
    ],
    translations: {
      br: 'Belgia',
      pt: 'Bélgica',
      nl: 'België',
      hr: 'Belgija',
      fa: 'بلژیک',
      de: 'Belgien',
      es: 'Bélgica',
      fr: 'Belgique',
      ja: 'ベルギー',
      it: 'Belgio',
      hu: 'Belgium',
    },
    flag: 'https://flagcdn.com/be.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'BEL',
    independent: true,
  },
  {
    name: 'Bosnia and Herzegovina',
    topLevelDomain: ['.ba'],
    alpha2Code: 'BA',
    alpha3Code: 'BIH',
    callingCodes: ['387'],
    capital: 'Sarajevo',
    altSpellings: ['BA', 'Bosnia-Herzegovina', 'Босна и Херцеговина'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 3280815,
    latlng: [44, 18],
    demonym: 'Bosnian, Herzegovinian',
    area: 51209,
    gini: 33,
    timezones: ['UTC+01:00'],
    borders: ['HRV', 'MNE', 'SRB'],
    nativeName: 'Bosna i Hercegovina',
    numericCode: '070',
    flags: {
      svg: 'https://flagcdn.com/ba.svg',
      png: 'https://flagcdn.com/w320/ba.png',
    },
    currencies: [
      {
        code: 'BAM',
        name: 'Bosnia and Herzegovina convertible mark',
        symbol: 'KM',
      },
    ],
    languages: [
      {
        iso639_1: 'bs',
        iso639_2: 'bos',
        name: 'Bosnian',
        nativeName: 'bosanski jezik',
      },
      {
        iso639_1: 'hr',
        iso639_2: 'hrv',
        name: 'Croatian',
        nativeName: 'hrvatski jezik',
      },
      {
        iso639_1: 'sr',
        iso639_2: 'srp',
        name: 'Serbian',
        nativeName: 'српски језик',
      },
    ],
    translations: {
      br: 'Bosnia-ha-Herzegovina',
      pt: 'Bósnia e Herzegovina',
      nl: 'Bosnië en Herzegovina',
      hr: 'Bosna i Hercegovina',
      fa: 'بوسنی و هرزگوین',
      de: 'Bosnien und Herzegowina',
      es: 'Bosnia y Herzegovina',
      fr: 'Bosnie-Herzégovine',
      ja: 'ボスニア・ヘルツェゴビナ',
      it: 'Bosnia ed Erzegovina',
      hu: 'Bosznia-Hercegovina',
    },
    flag: 'https://flagcdn.com/ba.svg',
    regionalBlocs: [
      {
        acronym: 'CEFTA',
        name: 'Central European Free Trade Agreement',
      },
    ],
    cioc: 'BIH',
    independent: true,
  },
  {
    name: 'Bulgaria',
    topLevelDomain: ['.bg'],
    alpha2Code: 'BG',
    alpha3Code: 'BGR',
    callingCodes: ['359'],
    capital: 'Sofia',
    altSpellings: ['BG', 'Republic of Bulgaria', 'Република България'],
    subregion: 'Eastern Europe',
    region: 'Europe',
    population: 6927288,
    latlng: [43, 25],
    demonym: 'Bulgarian',
    area: 110879,
    gini: 41.3,
    timezones: ['UTC+02:00'],
    borders: ['GRC', 'MKD', 'ROU', 'SRB', 'TUR'],
    nativeName: 'България',
    numericCode: '100',
    flags: {
      svg: 'https://flagcdn.com/bg.svg',
      png: 'https://flagcdn.com/w320/bg.png',
    },
    currencies: [
      {
        code: 'BGN',
        name: 'Bulgarian lev',
        symbol: 'лв',
      },
    ],
    languages: [
      {
        iso639_1: 'bg',
        iso639_2: 'bul',
        name: 'Bulgarian',
        nativeName: 'български език',
      },
    ],
    translations: {
      br: 'Bulgaria',
      pt: 'Bulgária',
      nl: 'Bulgarije',
      hr: 'Bugarska',
      fa: 'بلغارستان',
      de: 'Bulgarien',
      es: 'Bulgaria',
      fr: 'Bulgarie',
      ja: 'ブルガリア',
      it: 'Bulgaria',
      hu: 'Bulgária',
    },
    flag: 'https://flagcdn.com/bg.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'BUL',
    independent: true,
  },
  {
    name: 'Croatia',
    topLevelDomain: ['.hr'],
    alpha2Code: 'HR',
    alpha3Code: 'HRV',
    callingCodes: ['385'],
    capital: 'Zagreb',
    altSpellings: [
      'HR',
      'Hrvatska',
      'Republic of Croatia',
      'Republika Hrvatska',
    ],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 4047200,
    latlng: [45.16666666, 15.5],
    demonym: 'Croatian',
    area: 56594,
    gini: 29.7,
    timezones: ['UTC+01:00'],
    borders: ['BIH', 'HUN', 'MNE', 'SRB', 'SVN'],
    nativeName: 'Hrvatska',
    numericCode: '191',
    flags: {
      svg: 'https://flagcdn.com/hr.svg',
      png: 'https://flagcdn.com/w320/hr.png',
    },
    currencies: [
      {
        code: 'HRK',
        name: 'Croatian kuna',
        symbol: 'kn',
      },
    ],
    languages: [
      {
        iso639_1: 'hr',
        iso639_2: 'hrv',
        name: 'Croatian',
        nativeName: 'hrvatski jezik',
      },
    ],
    translations: {
      br: 'Kroatia',
      pt: 'Croácia',
      nl: 'Kroatië',
      hr: 'Hrvatska',
      fa: 'کرواسی',
      de: 'Kroatien',
      es: 'Croacia',
      fr: 'Croatie',
      ja: 'クロアチア',
      it: 'Croazia',
      hu: 'Horvátország',
    },
    flag: 'https://flagcdn.com/hr.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'CRO',
    independent: true,
  },
  {
    name: 'Cyprus',
    topLevelDomain: ['.cy'],
    alpha2Code: 'CY',
    alpha3Code: 'CYP',
    callingCodes: ['357'],
    capital: 'Nicosia',
    altSpellings: [
      'CY',
      'Kýpros',
      'Kıbrıs',
      'Republic of Cyprus',
      'Κυπριακή Δημοκρατία',
      'Kıbrıs Cumhuriyeti',
    ],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 1207361,
    latlng: [35, 33],
    demonym: 'Cypriot',
    area: 9251,
    gini: 32.7,
    timezones: ['UTC+02:00'],
    borders: ['GBR'],
    nativeName: 'Κύπρος',
    numericCode: '196',
    flags: {
      svg: 'https://flagcdn.com/cy.svg',
      png: 'https://flagcdn.com/w320/cy.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'el',
        iso639_2: 'ell',
        name: 'Greek (modern)',
        nativeName: 'ελληνικά',
      },
      {
        iso639_1: 'tr',
        iso639_2: 'tur',
        name: 'Turkish',
        nativeName: 'Türkçe',
      },
      {
        iso639_1: 'hy',
        iso639_2: 'hye',
        name: 'Armenian',
        nativeName: 'Հայերեն',
      },
    ],
    translations: {
      br: 'Kiprenez',
      pt: 'Chipre',
      nl: 'Cyprus',
      hr: 'Cipar',
      fa: 'قبرس',
      de: 'Zypern',
      es: 'Chipre',
      fr: 'Chypre',
      ja: 'キプロス',
      it: 'Cipro',
      hu: 'Ciprus',
    },
    flag: 'https://flagcdn.com/cy.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'CYP',
    independent: true,
  },
  {
    name: 'Czech Republic',
    topLevelDomain: ['.cz'],
    alpha2Code: 'CZ',
    alpha3Code: 'CZE',
    callingCodes: ['420'],
    capital: 'Prague',
    altSpellings: ['CZ', 'Česká republika', 'Česko'],
    subregion: 'Central Europe',
    region: 'Europe',
    population: 10698896,
    latlng: [49.75, 15.5],
    demonym: 'Czech',
    area: 78865,
    gini: 25,
    timezones: ['UTC+01:00'],
    nativeName: 'Česká republika',
    numericCode: '203',
    flags: {
      svg: 'https://flagcdn.com/cz.svg',
      png: 'https://flagcdn.com/w320/cz.png',
    },
    currencies: [
      {
        code: 'CZK',
        name: 'Czech koruna',
        symbol: 'Kč',
      },
    ],
    languages: [
      {
        iso639_1: 'cs',
        iso639_2: 'ces',
        name: 'Czech',
        nativeName: 'čeština',
      },
      {
        iso639_1: 'sk',
        iso639_2: 'slk',
        name: 'Slovak',
        nativeName: 'slovenčina',
      },
    ],
    translations: {
      br: 'Tchekia',
      pt: 'República Checa',
      nl: 'Tsjechië',
      hr: 'Češka',
      fa: 'جمهوری چک',
      de: 'Tschechische Republik',
      es: 'República Checa',
      fr: 'République tchèque',
      ja: 'チェコ',
      it: 'Repubblica Ceca',
      hu: 'Csehország',
    },
    flag: 'https://flagcdn.com/cz.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'CZE',
    independent: true,
  },
  {
    name: 'Denmark',
    topLevelDomain: ['.dk'],
    alpha2Code: 'DK',
    alpha3Code: 'DNK',
    callingCodes: ['45'],
    capital: 'Copenhagen',
    altSpellings: ['DK', 'Danmark', 'Kingdom of Denmark', 'Kongeriget Danmark'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 5831404,
    latlng: [56, 10],
    demonym: 'Danish',
    area: 43094,
    gini: 28.2,
    timezones: ['UTC-04:00', 'UTC-03:00', 'UTC-01:00', 'UTC', 'UTC+01:00'],
    borders: ['DEU'],
    nativeName: 'Danmark',
    numericCode: '208',
    flags: {
      svg: 'https://flagcdn.com/dk.svg',
      png: 'https://flagcdn.com/w320/dk.png',
    },
    currencies: [
      {
        code: 'DKK',
        name: 'Danish krone',
        symbol: 'kr',
      },
    ],
    languages: [
      {
        iso639_1: 'da',
        iso639_2: 'dan',
        name: 'Danish',
        nativeName: 'dansk',
      },
    ],
    translations: {
      br: 'Danmark',
      pt: 'Dinamarca',
      nl: 'Denemarken',
      hr: 'Danska',
      fa: 'دانمارک',
      de: 'Dänemark',
      es: 'Dinamarca',
      fr: 'Danemark',
      ja: 'デンマーク',
      it: 'Danimarca',
      hu: 'Dánia',
    },
    flag: 'https://flagcdn.com/dk.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'DEN',
    independent: true,
  },
  {
    name: 'Estonia',
    topLevelDomain: ['.ee'],
    alpha2Code: 'EE',
    alpha3Code: 'EST',
    callingCodes: ['372'],
    capital: 'Tallinn',
    altSpellings: ['EE', 'Eesti', 'Republic of Estonia', 'Eesti Vabariik'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 1331057,
    latlng: [59, 26],
    demonym: 'Estonian',
    area: 45227,
    gini: 30.3,
    timezones: ['UTC+02:00'],
    borders: ['LVA', 'RUS'],
    nativeName: 'Eesti',
    numericCode: '233',
    flags: {
      svg: 'https://flagcdn.com/ee.svg',
      png: 'https://flagcdn.com/w320/ee.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'et',
        iso639_2: 'est',
        name: 'Estonian',
        nativeName: 'eesti',
      },
    ],
    translations: {
      br: 'Estonia',
      pt: 'Estónia',
      nl: 'Estland',
      hr: 'Estonija',
      fa: 'استونی',
      de: 'Estland',
      es: 'Estonia',
      fr: 'Estonie',
      ja: 'エストニア',
      it: 'Estonia',
      hu: 'Észtország',
    },
    flag: 'https://flagcdn.com/ee.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'EST',
    independent: true,
  },
  {
    name: 'Faroe Islands',
    topLevelDomain: ['.fo'],
    alpha2Code: 'FO',
    alpha3Code: 'FRO',
    callingCodes: ['298'],
    capital: 'Tórshavn',
    altSpellings: ['FO', 'Føroyar', 'Færøerne'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 48865,
    latlng: [62, -7],
    demonym: 'Faroese',
    area: 1393,
    timezones: ['UTC+00:00'],
    nativeName: 'Føroyar',
    numericCode: '234',
    flags: {
      svg: 'https://flagcdn.com/fo.svg',
      png: 'https://flagcdn.com/w320/fo.png',
    },
    currencies: [
      {
        code: 'DKK',
        name: 'Danish krone',
        symbol: 'kr',
      },
      {
        code: 'FOK',
        name: 'Faroese króna',
        symbol: 'kr',
      },
    ],
    languages: [
      {
        iso639_1: 'fo',
        iso639_2: 'fao',
        name: 'Faroese',
        nativeName: 'føroyskt',
      },
    ],
    translations: {
      br: 'Inizi Faero',
      pt: 'Ilhas Faroé',
      nl: 'Faeröer',
      hr: 'Farski Otoci',
      fa: 'جزایر فارو',
      de: 'Färöer-Inseln',
      es: 'Islas Faroe',
      fr: 'Îles Féroé',
      ja: 'フェロー諸島',
      it: 'Isole Far Oer',
      hu: 'Feröer',
    },
    flag: 'https://flagcdn.com/fo.svg',
    independent: false,
  },
  {
    name: 'Finland',
    topLevelDomain: ['.fi'],
    alpha2Code: 'FI',
    alpha3Code: 'FIN',
    callingCodes: ['358'],
    capital: 'Helsinki',
    altSpellings: [
      'FI',
      'Suomi',
      'Republic of Finland',
      'Suomen tasavalta',
      'Republiken Finland',
    ],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 5530719,
    latlng: [64, 26],
    demonym: 'Finnish',
    area: 338424,
    gini: 27.3,
    timezones: ['UTC+02:00'],
    borders: ['NOR', 'SWE', 'RUS'],
    nativeName: 'Suomi',
    numericCode: '246',
    flags: {
      svg: 'https://flagcdn.com/fi.svg',
      png: 'https://flagcdn.com/w320/fi.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'fi',
        iso639_2: 'fin',
        name: 'Finnish',
        nativeName: 'suomi',
      },
      {
        iso639_1: 'sv',
        iso639_2: 'swe',
        name: 'Swedish',
        nativeName: 'svenska',
      },
    ],
    translations: {
      br: 'Finland',
      pt: 'Finlândia',
      nl: 'Finland',
      hr: 'Finska',
      fa: 'فنلاند',
      de: 'Finnland',
      es: 'Finlandia',
      fr: 'Finlande',
      ja: 'フィンランド',
      it: 'Finlandia',
      hu: 'Finnország',
    },
    flag: 'https://flagcdn.com/fi.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'FIN',
    independent: true,
  },
  {
    name: 'France',
    topLevelDomain: ['.fr'],
    alpha2Code: 'FR',
    alpha3Code: 'FRA',
    callingCodes: ['33'],
    capital: 'Paris',
    altSpellings: ['FR', 'French Republic', 'République française'],
    subregion: 'Western Europe',
    region: 'Europe',
    population: 67391582,
    latlng: [46, 2],
    demonym: 'French',
    area: 640679,
    gini: 32.4,
    timezones: [
      'UTC-10:00',
      'UTC-09:30',
      'UTC-09:00',
      'UTC-08:00',
      'UTC-04:00',
      'UTC-03:00',
      'UTC+01:00',
      'UTC+02:00',
      'UTC+03:00',
      'UTC+04:00',
      'UTC+05:00',
      'UTC+10:00',
      'UTC+11:00',
      'UTC+12:00',
    ],
    borders: ['AND', 'BEL', 'DEU', 'ITA', 'LUX', 'MCO', 'ESP', 'CHE'],
    nativeName: 'France',
    numericCode: '250',
    flags: {
      svg: 'https://flagcdn.com/fr.svg',
      png: 'https://flagcdn.com/w320/fr.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'fr',
        iso639_2: 'fra',
        name: 'French',
        nativeName: 'français',
      },
    ],
    translations: {
      br: 'Frañs',
      pt: 'França',
      nl: 'Frankrijk',
      hr: 'Francuska',
      fa: 'فرانسه',
      de: 'Frankreich',
      es: 'Francia',
      fr: 'France',
      ja: 'フランス',
      it: 'Francia',
      hu: 'Franciaország',
    },
    flag: 'https://flagcdn.com/fr.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'FRA',
    independent: true,
  },
  {
    name: 'Germany',
    topLevelDomain: ['.de'],
    alpha2Code: 'DE',
    alpha3Code: 'DEU',
    callingCodes: ['49'],
    capital: 'Berlin',
    altSpellings: [
      'DE',
      'Federal Republic of Germany',
      'Bundesrepublik Deutschland',
    ],
    subregion: 'Central Europe',
    region: 'Europe',
    population: 83240525,
    latlng: [51, 9],
    demonym: 'German',
    area: 357114,
    gini: 31.9,
    timezones: ['UTC+01:00'],
    borders: ['AUT', 'BEL', 'CZE', 'DNK', 'FRA', 'LUX', 'NLD', 'POL', 'CHE'],
    nativeName: 'Deutschland',
    numericCode: '276',
    flags: {
      svg: 'https://flagcdn.com/de.svg',
      png: 'https://flagcdn.com/w320/de.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'de',
        iso639_2: 'deu',
        name: 'German',
        nativeName: 'Deutsch',
      },
    ],
    translations: {
      br: 'Alamagn',
      pt: 'Alemanha',
      nl: 'Duitsland',
      hr: 'Njemačka',
      fa: 'آلمان',
      de: 'Deutschland',
      es: 'Alemania',
      fr: 'Allemagne',
      ja: 'ドイツ',
      it: 'Germania',
      hu: 'Grúzia',
    },
    flag: 'https://flagcdn.com/de.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'GER',
    independent: true,
  },
  {
    name: 'Gibraltar',
    topLevelDomain: ['.gi'],
    alpha2Code: 'GI',
    alpha3Code: 'GIB',
    callingCodes: ['350'],
    capital: 'Gibraltar',
    altSpellings: ['GI'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 33691,
    latlng: [36.13333333, -5.35],
    demonym: 'Gibraltar',
    area: 6,
    timezones: ['UTC+01:00'],
    borders: ['ESP'],
    nativeName: 'Gibraltar',
    numericCode: '292',
    flags: {
      svg: 'https://flagcdn.com/gi.svg',
      png: 'https://flagcdn.com/w320/gi.png',
    },
    currencies: [
      {
        code: 'GIP',
        name: 'Gibraltar pound',
        symbol: '£',
      },
    ],
    languages: [
      {
        iso639_1: 'en',
        iso639_2: 'eng',
        name: 'English',
        nativeName: 'English',
      },
    ],
    translations: {
      br: 'Jibraltar',
      pt: 'Gibraltar',
      nl: 'Gibraltar',
      hr: 'Gibraltar',
      fa: 'جبل‌طارق',
      de: 'Gibraltar',
      es: 'Gibraltar',
      fr: 'Gibraltar',
      ja: 'ジブラルタル',
      it: 'Gibilterra',
      hu: 'Gibraltár',
    },
    flag: 'https://flagcdn.com/gi.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    independent: false,
  },
  {
    name: 'Greece',
    topLevelDomain: ['.gr'],
    alpha2Code: 'GR',
    alpha3Code: 'GRC',
    callingCodes: ['30'],
    capital: 'Athens',
    altSpellings: ['GR', 'Elláda', 'Hellenic Republic', 'Ελληνική Δημοκρατία'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 10715549,
    latlng: [39, 22],
    demonym: 'Greek',
    area: 131990,
    gini: 32.9,
    timezones: ['UTC+02:00'],
    borders: ['ALB', 'BGR', 'TUR', 'MKD'],
    nativeName: 'Ελλάδα',
    numericCode: '300',
    flags: {
      svg: 'https://flagcdn.com/gr.svg',
      png: 'https://flagcdn.com/w320/gr.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'el',
        iso639_2: 'ell',
        name: 'Greek (modern)',
        nativeName: 'ελληνικά',
      },
    ],
    translations: {
      br: 'Gres',
      pt: 'Grécia',
      nl: 'Griekenland',
      hr: 'Grčka',
      fa: 'یونان',
      de: 'Griechenland',
      es: 'Grecia',
      fr: 'Grèce',
      ja: 'ギリシャ',
      it: 'Grecia',
      hu: 'Görögország',
    },
    flag: 'https://flagcdn.com/gr.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'GRE',
    independent: true,
  },
  {
    name: 'Guernsey',
    topLevelDomain: ['.gg'],
    alpha2Code: 'GG',
    alpha3Code: 'GGY',
    callingCodes: ['44'],
    capital: 'St. Peter Port',
    altSpellings: ['GG', 'Bailiwick of Guernsey', 'Bailliage de Guernesey'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 62999,
    latlng: [49.46666666, -2.58333333],
    demonym: 'Channel Islander',
    area: 78,
    timezones: ['UTC+00:00'],
    nativeName: 'Guernsey',
    numericCode: '831',
    flags: {
      svg: 'https://flagcdn.com/gg.svg',
      png: 'https://flagcdn.com/w320/gg.png',
    },
    currencies: [
      {
        code: 'GBP',
        name: 'British pound',
        symbol: '£',
      },
      {
        code: 'GGP',
        name: 'Guernsey pound',
        symbol: '£',
      },
    ],
    languages: [
      {
        iso639_1: 'en',
        iso639_2: 'eng',
        name: 'English',
        nativeName: 'English',
      },
      {
        iso639_1: 'fr',
        iso639_2: 'fra',
        name: 'French',
        nativeName: 'français',
      },
    ],
    translations: {
      br: 'Gwernenez',
      pt: 'Guernsey',
      nl: 'Guernsey',
      hr: 'Guernsey',
      fa: 'گرنزی',
      de: 'Guernsey',
      es: 'Guernsey',
      fr: 'Guernesey',
      ja: 'ガーンジー',
      it: 'Guernsey',
      hu: 'Guernsey',
    },
    flag: 'https://flagcdn.com/gg.svg',
    independent: false,
  },
  {
    name: 'Vatican City',
    topLevelDomain: ['.va'],
    alpha2Code: 'VA',
    alpha3Code: 'VAT',
    callingCodes: ['379'],
    capital: 'Vatican City',
    altSpellings: ['Vatican', 'The Vatican'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 451,
    latlng: [41.9, 12.45],
    demonym: 'Vatican',
    area: 0.44,
    timezones: ['UTC+01:00'],
    borders: ['ITA'],
    nativeName: 'Status Civitatis Vaticanae',
    numericCode: '336',
    flags: {
      svg: 'https://flagcdn.com/va.svg',
      png: 'https://flagcdn.com/w320/va.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'la',
        iso639_2: 'lat',
        name: 'Latin',
        nativeName: 'latine',
      },
      {
        iso639_1: 'it',
        iso639_2: 'ita',
        name: 'Italian',
        nativeName: 'Italiano',
      },
      {
        iso639_1: 'fr',
        iso639_2: 'fra',
        name: 'French',
        nativeName: 'Français',
      },
      {
        iso639_1: 'de',
        iso639_2: 'deu',
        name: 'German',
        nativeName: 'Deutsch',
      },
    ],
    translations: {
      br: 'Vatikan',
      pt: 'Vaticano',
      nl: 'Heilige Stoel',
      hr: 'Sveta Stolica',
      fa: 'سریر مقدس',
      de: 'Heiliger Stuhl',
      es: 'Santa Sede',
      fr: 'Saint-Siège',
      ja: '聖座',
      it: 'Santa Sede',
      hu: 'Vatikán',
    },
    flag: 'https://flagcdn.com/va.svg',
    independent: true,
  },
  {
    name: 'Hungary',
    topLevelDomain: ['.hu'],
    alpha2Code: 'HU',
    alpha3Code: 'HUN',
    callingCodes: ['36'],
    capital: 'Budapest',
    altSpellings: ['HU'],
    subregion: 'Central Europe',
    region: 'Europe',
    population: 9749763,
    latlng: [47, 20],
    demonym: 'Hungarian',
    area: 93028,
    gini: 29.6,
    timezones: ['UTC+01:00'],
    borders: ['AUT', 'HRV', 'ROU', 'SRB', 'SVK', 'SVN', 'UKR'],
    nativeName: 'Magyarország',
    numericCode: '348',
    flags: {
      svg: 'https://flagcdn.com/hu.svg',
      png: 'https://flagcdn.com/w320/hu.png',
    },
    currencies: [
      {
        code: 'HUF',
        name: 'Hungarian forint',
        symbol: 'Ft',
      },
    ],
    languages: [
      {
        iso639_1: 'hu',
        iso639_2: 'hun',
        name: 'Hungarian',
        nativeName: 'magyar',
      },
    ],
    translations: {
      br: 'Hungaria',
      pt: 'Hungria',
      nl: 'Hongarije',
      hr: 'Mađarska',
      fa: 'مجارستان',
      de: 'Ungarn',
      es: 'Hungría',
      fr: 'Hongrie',
      ja: 'ハンガリー',
      it: 'Ungheria',
      hu: 'Magyarország',
    },
    flag: 'https://flagcdn.com/hu.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'HUN',
    independent: true,
  },
  {
    name: 'Iceland',
    topLevelDomain: ['.is'],
    alpha2Code: 'IS',
    alpha3Code: 'ISL',
    callingCodes: ['354'],
    capital: 'Reykjavík',
    altSpellings: ['IS', 'Island', 'Republic of Iceland', 'Lýðveldið Ísland'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 366425,
    latlng: [65, -18],
    demonym: 'Icelander',
    area: 103000,
    gini: 26.1,
    timezones: ['UTC'],
    nativeName: 'Ísland',
    numericCode: '352',
    flags: {
      svg: 'https://flagcdn.com/is.svg',
      png: 'https://flagcdn.com/w320/is.png',
    },
    currencies: [
      {
        code: 'ISK',
        name: 'Icelandic króna',
        symbol: 'kr',
      },
    ],
    languages: [
      {
        iso639_1: 'is',
        iso639_2: 'isl',
        name: 'Icelandic',
        nativeName: 'Íslenska',
      },
    ],
    translations: {
      br: 'Island',
      pt: 'Islândia',
      nl: 'IJsland',
      hr: 'Island',
      fa: 'ایسلند',
      de: 'Island',
      es: 'Islandia',
      fr: 'Islande',
      ja: 'アイスランド',
      it: 'Islanda',
      hu: 'Izland',
    },
    flag: 'https://flagcdn.com/is.svg',
    regionalBlocs: [
      {
        acronym: 'EFTA',
        name: 'European Free Trade Association',
      },
    ],
    cioc: 'ISL',
    independent: true,
  },
  {
    name: 'Ireland',
    topLevelDomain: ['.ie'],
    alpha2Code: 'IE',
    alpha3Code: 'IRL',
    callingCodes: ['353'],
    capital: 'Dublin',
    altSpellings: ['IE', 'Éire', 'Republic of Ireland', 'Poblacht na hÉireann'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 4994724,
    latlng: [53, -8],
    demonym: 'Irish',
    area: 70273,
    gini: 31.4,
    timezones: ['UTC'],
    borders: ['GBR'],
    nativeName: 'Éire',
    numericCode: '372',
    flags: {
      svg: 'https://flagcdn.com/ie.svg',
      png: 'https://flagcdn.com/w320/ie.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'ga',
        iso639_2: 'gle',
        name: 'Irish',
        nativeName: 'Gaeilge',
      },
      {
        iso639_1: 'en',
        iso639_2: 'eng',
        name: 'English',
        nativeName: 'English',
      },
    ],
    translations: {
      br: 'Iwerzhon',
      pt: 'Irlanda',
      nl: 'Ierland',
      hr: 'Irska',
      fa: 'ایرلند',
      de: 'Irland',
      es: 'Irlanda',
      fr: 'Irlande',
      ja: 'アイルランド',
      it: 'Irlanda',
      hu: 'Írország',
    },
    flag: 'https://flagcdn.com/ie.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'IRL',
    independent: true,
  },
  {
    name: 'Isle of Man',
    topLevelDomain: ['.im'],
    alpha2Code: 'IM',
    alpha3Code: 'IMN',
    callingCodes: ['44'],
    capital: 'Douglas',
    altSpellings: ['IM', 'Ellan Vannin', 'Mann', 'Mannin'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 85032,
    latlng: [54.25, -4.5],
    demonym: 'Manx',
    area: 572,
    timezones: ['UTC+00:00'],
    nativeName: 'Isle of Man',
    numericCode: '833',
    flags: {
      svg: 'https://flagcdn.com/im.svg',
      png: 'https://flagcdn.com/w320/im.png',
    },
    currencies: [
      {
        code: 'GBP',
        name: 'British pound',
        symbol: '£',
      },
      {
        code: 'IMP[G]',
        name: 'Manx pound',
        symbol: '£',
      },
    ],
    languages: [
      {
        iso639_1: 'en',
        iso639_2: 'eng',
        name: 'English',
        nativeName: 'English',
      },
      {
        iso639_1: 'gv',
        iso639_2: 'glv',
        name: 'Manx',
        nativeName: 'Gaelg',
      },
    ],
    translations: {
      br: 'Enez Vanav',
      pt: 'Ilha de Man',
      nl: 'Isle of Man',
      hr: 'Otok Man',
      fa: 'جزیره من',
      de: 'Insel Man',
      es: 'Isla de Man',
      fr: 'Île de Man',
      ja: 'マン島',
      it: 'Isola di Man',
      hu: 'Man',
    },
    flag: 'https://flagcdn.com/im.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    independent: false,
  },
  {
    name: 'Italy',
    topLevelDomain: ['.it'],
    alpha2Code: 'IT',
    alpha3Code: 'ITA',
    callingCodes: ['39'],
    capital: 'Rome',
    altSpellings: ['IT', 'Italian Republic', 'Repubblica italiana'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 59554023,
    latlng: [42.83333333, 12.83333333],
    demonym: 'Italian',
    area: 301336,
    gini: 35.9,
    timezones: ['UTC+01:00'],
    borders: ['AUT', 'FRA', 'SMR', 'SVN', 'CHE', 'VAT'],
    nativeName: 'Italia',
    numericCode: '380',
    flags: {
      svg: 'https://flagcdn.com/it.svg',
      png: 'https://flagcdn.com/w320/it.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'it',
        iso639_2: 'ita',
        name: 'Italian',
        nativeName: 'Italiano',
      },
    ],
    translations: {
      br: 'Italia',
      pt: 'Itália',
      nl: 'Italië',
      hr: 'Italija',
      fa: 'ایتالیا',
      de: 'Italien',
      es: 'Italia',
      fr: 'Italie',
      ja: 'イタリア',
      it: 'Italia',
      hu: 'Olaszország',
    },
    flag: 'https://flagcdn.com/it.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'ITA',
    independent: true,
  },
  {
    name: 'Jersey',
    topLevelDomain: ['.je'],
    alpha2Code: 'JE',
    alpha3Code: 'JEY',
    callingCodes: ['44'],
    capital: 'Saint Helier',
    altSpellings: [
      'JE',
      'Bailiwick of Jersey',
      'Bailliage de Jersey',
      'Bailliage dé Jèrri',
    ],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 100800,
    latlng: [49.25, -2.16666666],
    demonym: 'Channel Islander',
    area: 116,
    timezones: ['UTC+01:00'],
    nativeName: 'Jersey',
    numericCode: '832',
    flags: {
      svg: 'https://flagcdn.com/je.svg',
      png: 'https://flagcdn.com/w320/je.png',
    },
    currencies: [
      {
        code: 'GBP',
        name: 'British pound',
        symbol: '£',
      },
      {
        code: 'JEP[G]',
        name: 'Jersey pound',
        symbol: '£',
      },
    ],
    languages: [
      {
        iso639_1: 'en',
        iso639_2: 'eng',
        name: 'English',
        nativeName: 'English',
      },
      {
        iso639_1: 'fr',
        iso639_2: 'fra',
        name: 'French',
        nativeName: 'français',
      },
    ],
    translations: {
      br: 'Jerzenez',
      pt: 'Jersey',
      nl: 'Jersey',
      hr: 'Jersey',
      fa: 'جرزی',
      de: 'Jersey',
      es: 'Jersey',
      fr: 'Jersey',
      ja: 'ジャージー',
      it: 'Isola di Jersey',
      hu: 'Jersey',
    },
    flag: 'https://flagcdn.com/je.svg',
    independent: false,
  },
  {
    name: 'Latvia',
    topLevelDomain: ['.lv'],
    alpha2Code: 'LV',
    alpha3Code: 'LVA',
    callingCodes: ['371'],
    capital: 'Riga',
    altSpellings: ['LV', 'Republic of Latvia', 'Latvijas Republika'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 1901548,
    latlng: [57, 25],
    demonym: 'Latvian',
    area: 64559,
    gini: 35.1,
    timezones: ['UTC+02:00'],
    borders: ['BLR', 'EST', 'LTU', 'RUS'],
    nativeName: 'Latvija',
    numericCode: '428',
    flags: {
      svg: 'https://flagcdn.com/lv.svg',
      png: 'https://flagcdn.com/w320/lv.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'lv',
        iso639_2: 'lav',
        name: 'Latvian',
        nativeName: 'latviešu valoda',
      },
    ],
    translations: {
      br: 'Latvia',
      pt: 'Letónia',
      nl: 'Letland',
      hr: 'Latvija',
      fa: 'لتونی',
      de: 'Lettland',
      es: 'Letonia',
      fr: 'Lettonie',
      ja: 'ラトビア',
      it: 'Lettonia',
      hu: 'Lettország',
    },
    flag: 'https://flagcdn.com/lv.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'LAT',
    independent: true,
  },
  {
    name: 'Liechtenstein',
    topLevelDomain: ['.li'],
    alpha2Code: 'LI',
    alpha3Code: 'LIE',
    callingCodes: ['423'],
    capital: 'Vaduz',
    altSpellings: [
      'LI',
      'Principality of Liechtenstein',
      'Fürstentum Liechtenstein',
    ],
    subregion: 'Central Europe',
    region: 'Europe',
    population: 38137,
    latlng: [47.26666666, 9.53333333],
    demonym: 'Liechtensteiner',
    area: 160,
    timezones: ['UTC+01:00'],
    borders: ['AUT', 'CHE'],
    nativeName: 'Liechtenstein',
    numericCode: '438',
    flags: {
      svg: 'https://flagcdn.com/li.svg',
      png: 'https://flagcdn.com/w320/li.png',
    },
    currencies: [
      {
        code: 'CHF',
        name: 'Swiss franc',
        symbol: 'Fr',
      },
    ],
    languages: [
      {
        iso639_1: 'de',
        iso639_2: 'deu',
        name: 'German',
        nativeName: 'Deutsch',
      },
    ],
    translations: {
      br: 'Liechtenstein',
      pt: 'Listenstaine',
      nl: 'Liechtenstein',
      hr: 'Lihtenštajn',
      fa: 'لیختن‌اشتاین',
      de: 'Liechtenstein',
      es: 'Liechtenstein',
      fr: 'Liechtenstein',
      ja: 'リヒテンシュタイン',
      it: 'Liechtenstein',
      hu: 'Liechtenstein',
    },
    flag: 'https://flagcdn.com/li.svg',
    regionalBlocs: [
      {
        acronym: 'EFTA',
        name: 'European Free Trade Association',
      },
    ],
    cioc: 'LIE',
    independent: true,
  },
  {
    name: 'Lithuania',
    topLevelDomain: ['.lt'],
    alpha2Code: 'LT',
    alpha3Code: 'LTU',
    callingCodes: ['370'],
    capital: 'Vilnius',
    altSpellings: ['LT', 'Republic of Lithuania', 'Lietuvos Respublika'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 2794700,
    latlng: [56, 24],
    demonym: 'Lithuanian',
    area: 65300,
    gini: 35.7,
    timezones: ['UTC+02:00'],
    borders: ['BLR', 'LVA', 'POL', 'RUS'],
    nativeName: 'Lietuva',
    numericCode: '440',
    flags: {
      svg: 'https://flagcdn.com/lt.svg',
      png: 'https://flagcdn.com/w320/lt.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'lt',
        iso639_2: 'lit',
        name: 'Lithuanian',
        nativeName: 'lietuvių kalba',
      },
    ],
    translations: {
      br: 'Lituania',
      pt: 'Lituânia',
      nl: 'Litouwen',
      hr: 'Litva',
      fa: 'لیتوانی',
      de: 'Litauen',
      es: 'Lituania',
      fr: 'Lituanie',
      ja: 'リトアニア',
      it: 'Lituania',
      hu: 'Litvánia',
    },
    flag: 'https://flagcdn.com/lt.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'LTU',
    independent: true,
  },
  {
    name: 'Luxembourg',
    topLevelDomain: ['.lu'],
    alpha2Code: 'LU',
    alpha3Code: 'LUX',
    callingCodes: ['352'],
    capital: 'Luxembourg',
    altSpellings: [
      'LU',
      'Grand Duchy of Luxembourg',
      'Grand-Duché de Luxembourg',
      'Großherzogtum Luxemburg',
      'Groussherzogtum Lëtzebuerg',
    ],
    subregion: 'Western Europe',
    region: 'Europe',
    population: 632275,
    latlng: [49.75, 6.16666666],
    demonym: 'Luxembourger',
    area: 2586,
    gini: 35.4,
    timezones: ['UTC+01:00'],
    borders: ['BEL', 'FRA', 'DEU'],
    nativeName: 'Lëtzebuerg',
    numericCode: '442',
    flags: {
      svg: 'https://flagcdn.com/lu.svg',
      png: 'https://flagcdn.com/w320/lu.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'fr',
        iso639_2: 'fra',
        name: 'French',
        nativeName: 'français',
      },
      {
        iso639_1: 'de',
        iso639_2: 'deu',
        name: 'German',
        nativeName: 'Deutsch',
      },
      {
        iso639_1: 'lb',
        iso639_2: 'ltz',
        name: 'Luxembourgish',
        nativeName: 'Lëtzebuergesch',
      },
    ],
    translations: {
      br: 'Luksembourg',
      pt: 'Luxemburgo',
      nl: 'Luxemburg',
      hr: 'Luksemburg',
      fa: 'لوکزامبورگ',
      de: 'Luxemburg',
      es: 'Luxemburgo',
      fr: 'Luxembourg',
      ja: 'ルクセンブルク',
      it: 'Lussemburgo',
      hu: 'Luxemburg',
    },
    flag: 'https://flagcdn.com/lu.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'LUX',
    independent: true,
  },
  {
    name: 'North Macedonia',
    topLevelDomain: ['.mk'],
    alpha2Code: 'MK',
    alpha3Code: 'MKD',
    callingCodes: ['389'],
    capital: 'Skopje',
    altSpellings: ['MK', 'Republic of Macedonia', 'Република Македонија'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 2083380,
    latlng: [41.83333333, 22],
    demonym: 'Macedonian',
    area: 25713,
    gini: 33,
    timezones: ['UTC+01:00'],
    borders: ['ALB', 'BGR', 'GRC', 'UNK', 'SRB'],
    nativeName: 'Македонија',
    numericCode: '807',
    flags: {
      svg: 'https://flagcdn.com/mk.svg',
      png: 'https://flagcdn.com/w320/mk.png',
    },
    currencies: [
      {
        code: 'MKD',
        name: 'Macedonian denar',
        symbol: 'ден',
      },
    ],
    languages: [
      {
        iso639_1: 'mk',
        iso639_2: 'mkd',
        name: 'Macedonian',
        nativeName: 'македонски јазик',
      },
    ],
    translations: {
      br: 'Makedonia an Norzh',
      pt: 'Macedónia',
      nl: 'Macedonië',
      hr: 'Makedonija',
      de: 'Mazedonien',
      es: 'Macedonia',
      fr: 'Macédoine',
      ja: 'マケドニア旧ユーゴスラビア共和国',
      it: 'Macedonia',
      hu: 'Macedónia',
    },
    flag: 'https://flagcdn.com/mk.svg',
    regionalBlocs: [
      {
        acronym: 'CEFTA',
        name: 'Central European Free Trade Agreement',
      },
    ],
    cioc: 'MKD',
    independent: true,
  },
  {
    name: 'Malta',
    topLevelDomain: ['.mt'],
    alpha2Code: 'MT',
    alpha3Code: 'MLT',
    callingCodes: ['356'],
    capital: 'Valletta',
    altSpellings: ['MT', 'Republic of Malta', "Repubblika ta' Malta"],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 525285,
    latlng: [35.83333333, 14.58333333],
    demonym: 'Maltese',
    area: 316,
    gini: 28.7,
    timezones: ['UTC+01:00'],
    nativeName: 'Malta',
    numericCode: '470',
    flags: {
      svg: 'https://flagcdn.com/mt.svg',
      png: 'https://flagcdn.com/w320/mt.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'mt',
        iso639_2: 'mlt',
        name: 'Maltese',
        nativeName: 'Malti',
      },
      {
        iso639_1: 'en',
        iso639_2: 'eng',
        name: 'English',
        nativeName: 'English',
      },
    ],
    translations: {
      br: 'Malta',
      pt: 'Malta',
      nl: 'Malta',
      hr: 'Malta',
      fa: 'مالت',
      de: 'Malta',
      es: 'Malta',
      fr: 'Malte',
      ja: 'マルタ',
      it: 'Malta',
      hu: 'Málta',
    },
    flag: 'https://flagcdn.com/mt.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'MLT',
    independent: true,
  },
  {
    name: 'Moldova (Republic of)',
    topLevelDomain: ['.md'],
    alpha2Code: 'MD',
    alpha3Code: 'MDA',
    callingCodes: ['373'],
    capital: 'Chișinău',
    altSpellings: ['MD', 'Republic of Moldova', 'Republica Moldova'],
    subregion: 'Eastern Europe',
    region: 'Europe',
    population: 2617820,
    latlng: [47, 29],
    demonym: 'Moldovan',
    area: 33846,
    gini: 25.7,
    timezones: ['UTC+02:00'],
    borders: ['ROU', 'UKR'],
    nativeName: 'Moldova',
    numericCode: '498',
    flags: {
      svg: 'https://flagcdn.com/md.svg',
      png: 'https://flagcdn.com/w320/md.png',
    },
    currencies: [
      {
        code: 'MDL',
        name: 'Moldovan leu',
        symbol: 'L',
      },
    ],
    languages: [
      {
        iso639_1: 'ro',
        iso639_2: 'ron',
        name: 'Romanian',
        nativeName: 'Română',
      },
    ],
    translations: {
      br: 'Moldova',
      pt: 'Moldávia',
      nl: 'Moldavië',
      hr: 'Moldova',
      fa: 'مولداوی',
      de: 'Moldawie',
      es: 'Moldavia',
      fr: 'Moldavie',
      ja: 'モルドバ共和国',
      it: 'Moldavia',
      hu: 'Moldova',
    },
    flag: 'https://flagcdn.com/md.svg',
    regionalBlocs: [
      {
        acronym: 'CEFTA',
        name: 'Central European Free Trade Agreement',
      },
    ],
    cioc: 'MDA',
    independent: true,
  },
  {
    name: 'Monaco',
    topLevelDomain: ['.mc'],
    alpha2Code: 'MC',
    alpha3Code: 'MCO',
    callingCodes: ['377'],
    capital: 'Monaco',
    altSpellings: ['MC', 'Principality of Monaco', 'Principauté de Monaco'],
    subregion: 'Western Europe',
    region: 'Europe',
    population: 39244,
    latlng: [43.73333333, 7.4],
    demonym: 'Monegasque',
    area: 2.02,
    timezones: ['UTC+01:00'],
    borders: ['FRA'],
    nativeName: 'Monaco',
    numericCode: '492',
    flags: {
      svg: 'https://flagcdn.com/mc.svg',
      png: 'https://flagcdn.com/w320/mc.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'fr',
        iso639_2: 'fra',
        name: 'French',
        nativeName: 'français',
      },
    ],
    translations: {
      br: 'Monako',
      pt: 'Mónaco',
      nl: 'Monaco',
      hr: 'Monako',
      fa: 'موناکو',
      de: 'Monaco',
      es: 'Mónaco',
      fr: 'Monaco',
      ja: 'モナコ',
      it: 'Principato di Monaco',
      hu: 'Monaco',
    },
    flag: 'https://flagcdn.com/mc.svg',
    cioc: 'MON',
    independent: true,
  },
  {
    name: 'Montenegro',
    topLevelDomain: ['.me'],
    alpha2Code: 'ME',
    alpha3Code: 'MNE',
    callingCodes: ['382'],
    capital: 'Podgorica',
    altSpellings: ['ME', 'Crna Gora'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 621718,
    latlng: [42.5, 19.3],
    demonym: 'Montenegrin',
    area: 13812,
    gini: 38.5,
    timezones: ['UTC+01:00'],
    borders: ['ALB', 'BIH', 'HRV', 'UNK', 'SRB'],
    nativeName: 'Црна Гора',
    numericCode: '499',
    flags: {
      svg: 'https://flagcdn.com/me.svg',
      png: 'https://flagcdn.com/w320/me.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'sr',
        iso639_2: 'srp',
        name: 'Serbian',
        nativeName: 'српски језик',
      },
      {
        iso639_1: 'bs',
        iso639_2: 'bos',
        name: 'Bosnian',
        nativeName: 'bosanski jezik',
      },
      {
        iso639_1: 'sq',
        iso639_2: 'sqi',
        name: 'Albanian',
        nativeName: 'Shqip',
      },
      {
        iso639_1: 'hr',
        iso639_2: 'hrv',
        name: 'Croatian',
        nativeName: 'hrvatski jezik',
      },
    ],
    translations: {
      br: 'Montenegro',
      pt: 'Montenegro',
      nl: 'Montenegro',
      hr: 'Crna Gora',
      fa: 'مونته‌نگرو',
      de: 'Montenegro',
      es: 'Montenegro',
      fr: 'Monténégro',
      ja: 'モンテネグロ',
      it: 'Montenegro',
      hu: 'Montenegró',
    },
    flag: 'https://flagcdn.com/me.svg',
    regionalBlocs: [
      {
        acronym: 'CEFTA',
        name: 'Central European Free Trade Agreement',
      },
    ],
    cioc: 'MNE',
    independent: true,
  },
  {
    name: 'Netherlands',
    topLevelDomain: ['.nl'],
    alpha2Code: 'NL',
    alpha3Code: 'NLD',
    callingCodes: ['31'],
    capital: 'Amsterdam',
    altSpellings: ['NL', 'Holland', 'Nederland'],
    subregion: 'Western Europe',
    region: 'Europe',
    population: 17441139,
    latlng: [52.5, 5.75],
    demonym: 'Dutch',
    area: 41850,
    gini: 28.1,
    timezones: ['UTC-04:00', 'UTC+01:00'],
    borders: ['BEL', 'DEU'],
    nativeName: 'Nederland',
    numericCode: '528',
    flags: {
      svg: 'https://flagcdn.com/nl.svg',
      png: 'https://flagcdn.com/w320/nl.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'nl',
        iso639_2: 'nld',
        name: 'Dutch',
        nativeName: 'Nederlands',
      },
    ],
    translations: {
      br: 'Izelvroioù',
      pt: 'Países Baixos',
      nl: 'Nederland',
      hr: 'Nizozemska',
      fa: 'پادشاهی هلند',
      de: 'Niederlande',
      es: 'Países Bajos',
      fr: 'Pays-Bas',
      ja: 'オランダ',
      it: 'Paesi Bassi',
      hu: 'Hollandia',
    },
    flag: 'https://flagcdn.com/nl.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'NED',
    independent: true,
  },
  {
    name: 'Norway',
    topLevelDomain: ['.no'],
    alpha2Code: 'NO',
    alpha3Code: 'NOR',
    callingCodes: ['47'],
    capital: 'Oslo',
    altSpellings: [
      'NO',
      'Norge',
      'Noreg',
      'Kingdom of Norway',
      'Kongeriket Norge',
      'Kongeriket Noreg',
    ],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 5379475,
    latlng: [62, 10],
    demonym: 'Norwegian',
    area: 323802,
    gini: 27.6,
    timezones: ['UTC+01:00'],
    borders: ['FIN', 'SWE', 'RUS'],
    nativeName: 'Norge',
    numericCode: '578',
    flags: {
      svg: 'https://flagcdn.com/no.svg',
      png: 'https://flagcdn.com/w320/no.png',
    },
    currencies: [
      {
        code: 'NOK',
        name: 'Norwegian krone',
        symbol: 'kr',
      },
    ],
    languages: [
      {
        iso639_1: 'no',
        iso639_2: 'nor',
        name: 'Norwegian',
        nativeName: 'Norsk',
      },
      {
        iso639_1: 'nb',
        iso639_2: 'nob',
        name: 'Norwegian Bokmål',
        nativeName: 'Norsk bokmål',
      },
      {
        iso639_1: 'nn',
        iso639_2: 'nno',
        name: 'Norwegian Nynorsk',
        nativeName: 'Norsk nynorsk',
      },
    ],
    translations: {
      br: 'Norvegia',
      pt: 'Noruega',
      nl: 'Noorwegen',
      hr: 'Norveška',
      fa: 'نروژ',
      de: 'Norwegen',
      es: 'Noruega',
      fr: 'Norvège',
      ja: 'ノルウェー',
      it: 'Norvegia',
      hu: 'Norvégia',
    },
    flag: 'https://flagcdn.com/no.svg',
    regionalBlocs: [
      {
        acronym: 'EFTA',
        name: 'European Free Trade Association',
      },
    ],
    cioc: 'NOR',
    independent: true,
  },
  {
    name: 'Poland',
    topLevelDomain: ['.pl'],
    alpha2Code: 'PL',
    alpha3Code: 'POL',
    callingCodes: ['48'],
    capital: 'Warsaw',
    altSpellings: ['PL', 'Republic of Poland', 'Rzeczpospolita Polska'],
    subregion: 'Central Europe',
    region: 'Europe',
    population: 37950802,
    latlng: [52, 20],
    demonym: 'Polish',
    area: 312679,
    gini: 30.2,
    timezones: ['UTC+01:00'],
    borders: ['BLR', 'CZE', 'DEU', 'LTU', 'RUS', 'SVK', 'UKR'],
    nativeName: 'Polska',
    numericCode: '616',
    flags: {
      svg: 'https://flagcdn.com/pl.svg',
      png: 'https://flagcdn.com/w320/pl.png',
    },
    currencies: [
      {
        code: 'PLN',
        name: 'Polish złoty',
        symbol: 'zł',
      },
    ],
    languages: [
      {
        iso639_1: 'pl',
        iso639_2: 'pol',
        name: 'Polish',
        nativeName: 'język polski',
      },
    ],
    translations: {
      br: 'Polonia',
      pt: 'Polónia',
      nl: 'Polen',
      hr: 'Poljska',
      fa: 'لهستان',
      de: 'Polen',
      es: 'Polonia',
      fr: 'Pologne',
      ja: 'ポーランド',
      it: 'Polonia',
      hu: 'Lengyelország',
    },
    flag: 'https://flagcdn.com/pl.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'POL',
    independent: true,
  },
  {
    name: 'Portugal',
    topLevelDomain: ['.pt'],
    alpha2Code: 'PT',
    alpha3Code: 'PRT',
    callingCodes: ['351'],
    capital: 'Lisbon',
    altSpellings: [
      'PT',
      'Portuguesa',
      'Portuguese Republic',
      'República Portuguesa',
    ],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 10305564,
    latlng: [39.5, -8],
    demonym: 'Portuguese',
    area: 92090,
    gini: 33.5,
    timezones: ['UTC-01:00', 'UTC'],
    borders: ['ESP'],
    nativeName: 'Portugal',
    numericCode: '620',
    flags: {
      svg: 'https://flagcdn.com/pt.svg',
      png: 'https://flagcdn.com/w320/pt.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'pt',
        iso639_2: 'por',
        name: 'Portuguese',
        nativeName: 'Português',
      },
    ],
    translations: {
      br: 'Portugal',
      pt: 'Portugal',
      nl: 'Portugal',
      hr: 'Portugal',
      fa: 'پرتغال',
      de: 'Portugal',
      es: 'Portugal',
      fr: 'Portugal',
      ja: 'ポルトガル',
      it: 'Portogallo',
      hu: 'Portugália',
    },
    flag: 'https://flagcdn.com/pt.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'POR',
    independent: true,
  },
  {
    name: 'Republic of Kosovo',
    topLevelDomain: [''],
    alpha2Code: 'XK',
    alpha3Code: 'UNK',
    callingCodes: ['383'],
    capital: 'Pristina',
    altSpellings: ['XK', 'Република Косово'],
    subregion: 'Eastern Europe',
    region: 'Europe',
    population: 1775378,
    latlng: [42.666667, 21.166667],
    demonym: 'Kosovar',
    area: 10908,
    gini: 29,
    timezones: ['UTC+01:00'],
    borders: ['ALB', 'MKD', 'MNE', 'SRB'],
    nativeName: 'Republika e Kosovës',
    numericCode: '926',
    flags: {
      svg: 'https://flagcdn.com/xk.svg',
      png: 'https://flagcdn.com/w320/xk.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'sq',
        iso639_2: 'sqi',
        name: 'Albanian',
        nativeName: 'Shqip',
      },
      {
        iso639_1: 'sr',
        iso639_2: 'srp',
        name: 'Serbian',
        nativeName: 'српски језик',
      },
    ],
    translations: {
      br: 'Kosovo',
      pt: 'Kosovo',
      nl: 'Republiek van Kosovo',
      hr: 'Kosovo',
      fa: 'کوزوو',
      de: 'Republic of Kosovo',
      es: 'Kosovo',
      fr: 'Kosovo',
      ja: 'Republic of Kosovo',
      it: 'Republic of Kosovo',
      hu: 'Koszovó',
    },
    flag: 'https://flagcdn.com/xk.svg',
    regionalBlocs: [
      {
        acronym: 'CEFTA',
        name: 'Central European Free Trade Agreement',
      },
    ],
    independent: true,
  },
  {
    name: 'Romania',
    topLevelDomain: ['.ro'],
    alpha2Code: 'RO',
    alpha3Code: 'ROU',
    callingCodes: ['40'],
    capital: 'Bucharest',
    altSpellings: ['RO', 'Rumania', 'Roumania', 'România'],
    subregion: 'Eastern Europe',
    region: 'Europe',
    population: 19286123,
    latlng: [46, 25],
    demonym: 'Romanian',
    area: 238391,
    gini: 35.8,
    timezones: ['UTC+02:00'],
    borders: ['BGR', 'HUN', 'MDA', 'SRB', 'UKR'],
    nativeName: 'România',
    numericCode: '642',
    flags: {
      svg: 'https://flagcdn.com/ro.svg',
      png: 'https://flagcdn.com/w320/ro.png',
    },
    currencies: [
      {
        code: 'RON',
        name: 'Romanian leu',
        symbol: 'lei',
      },
    ],
    languages: [
      {
        iso639_1: 'ro',
        iso639_2: 'ron',
        name: 'Romanian',
        nativeName: 'Română',
      },
    ],
    translations: {
      br: 'Roumania',
      pt: 'Roménia',
      nl: 'Roemenië',
      hr: 'Rumunjska',
      fa: 'رومانی',
      de: 'Rumänien',
      es: 'Rumania',
      fr: 'Roumanie',
      ja: 'ルーマニア',
      it: 'Romania',
      hu: 'Románia',
    },
    flag: 'https://flagcdn.com/ro.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'ROU',
    independent: true,
  },
  {
    name: 'Russian Federation',
    topLevelDomain: ['.ru'],
    alpha2Code: 'RU',
    alpha3Code: 'RUS',
    callingCodes: ['7'],
    capital: 'Moscow',
    altSpellings: [
      'RU',
      'Rossiya',
      'Russian Federation',
      'Российская Федерация',
      'Rossiyskaya Federatsiya',
    ],
    subregion: 'Eastern Europe',
    region: 'Europe',
    population: 144104080,
    latlng: [60, 100],
    demonym: 'Russian',
    area: 17124442,
    gini: 37.5,
    timezones: [
      'UTC+03:00',
      'UTC+04:00',
      'UTC+06:00',
      'UTC+07:00',
      'UTC+08:00',
      'UTC+09:00',
      'UTC+10:00',
      'UTC+11:00',
      'UTC+12:00',
    ],
    borders: [
      'AZE',
      'BLR',
      'CHN',
      'EST',
      'FIN',
      'GEO',
      'KAZ',
      'PRK',
      'LVA',
      'LTU',
      'MNG',
      'NOR',
      'POL',
      'UKR',
    ],
    nativeName: 'Россия',
    numericCode: '643',
    flags: {
      svg: 'https://flagcdn.com/ru.svg',
      png: 'https://flagcdn.com/w320/ru.png',
    },
    currencies: [
      {
        code: 'RUB',
        name: 'Russian ruble',
        symbol: '₽',
      },
    ],
    languages: [
      {
        iso639_1: 'ru',
        iso639_2: 'rus',
        name: 'Russian',
        nativeName: 'Русский',
      },
    ],
    translations: {
      br: 'Rusia',
      pt: 'Rússia',
      nl: 'Rusland',
      hr: 'Rusija',
      fa: 'روسیه',
      de: 'Russland',
      es: 'Rusia',
      fr: 'Russie',
      ja: 'ロシア連邦',
      it: 'Russia',
      hu: 'Oroszország',
    },
    flag: 'https://flagcdn.com/ru.svg',
    regionalBlocs: [
      {
        acronym: 'EEU',
        name: 'Eurasian Economic Union',
        otherAcronyms: ['EAEU'],
      },
    ],
    cioc: 'RUS',
    independent: true,
  },
  {
    name: 'San Marino',
    topLevelDomain: ['.sm'],
    alpha2Code: 'SM',
    alpha3Code: 'SMR',
    callingCodes: ['378'],
    capital: 'City of San Marino',
    altSpellings: ['SM', 'Republic of San Marino', 'Repubblica di San Marino'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 33938,
    latlng: [43.76666666, 12.41666666],
    demonym: 'Sammarinese',
    area: 61,
    timezones: ['UTC+01:00'],
    borders: ['ITA'],
    nativeName: 'San Marino',
    numericCode: '674',
    flags: {
      svg: 'https://flagcdn.com/sm.svg',
      png: 'https://flagcdn.com/w320/sm.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'it',
        iso639_2: 'ita',
        name: 'Italian',
        nativeName: 'Italiano',
      },
    ],
    translations: {
      br: 'San Marino',
      pt: 'São Marinho',
      nl: 'San Marino',
      hr: 'San Marino',
      fa: 'سان مارینو',
      de: 'San Marino',
      es: 'San Marino',
      fr: 'Saint-Marin',
      ja: 'サンマリノ',
      it: 'San Marino',
      hu: 'San Marino',
    },
    flag: 'https://flagcdn.com/sm.svg',
    cioc: 'SMR',
    independent: true,
  },
  {
    name: 'Serbia',
    topLevelDomain: ['.rs'],
    alpha2Code: 'RS',
    alpha3Code: 'SRB',
    callingCodes: ['381'],
    capital: 'Belgrade',
    altSpellings: [
      'RS',
      'Srbija',
      'Republic of Serbia',
      'Република Србија',
      'Republika Srbija',
    ],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 6908224,
    latlng: [44, 21],
    demonym: 'Serbian',
    area: 88361,
    gini: 36.2,
    timezones: ['UTC+01:00'],
    borders: ['BIH', 'BGR', 'HRV', 'HUN', 'UNK', 'MKD', 'MNE', 'ROU'],
    nativeName: 'Србија',
    numericCode: '688',
    flags: {
      svg: 'https://flagcdn.com/rs.svg',
      png: 'https://flagcdn.com/w320/rs.png',
    },
    currencies: [
      {
        code: 'RSD',
        name: 'Serbian dinar',
        symbol: 'дин.',
      },
    ],
    languages: [
      {
        iso639_1: 'sr',
        iso639_2: 'srp',
        name: 'Serbian',
        nativeName: 'српски језик',
      },
    ],
    translations: {
      br: 'Serbia',
      pt: 'Sérvia',
      nl: 'Servië',
      hr: 'Srbija',
      fa: 'صربستان',
      de: 'Serbien',
      es: 'Serbia',
      fr: 'Serbie',
      ja: 'セルビア',
      it: 'Serbia',
      hu: 'Szerbia',
    },
    flag: 'https://flagcdn.com/rs.svg',
    regionalBlocs: [
      {
        acronym: 'CEFTA',
        name: 'Central European Free Trade Agreement',
      },
    ],
    cioc: 'SRB',
    independent: true,
  },
  {
    name: 'Slovakia',
    topLevelDomain: ['.sk'],
    alpha2Code: 'SK',
    alpha3Code: 'SVK',
    callingCodes: ['421'],
    capital: 'Bratislava',
    altSpellings: ['SK', 'Slovak Republic', 'Slovenská republika'],
    subregion: 'Central Europe',
    region: 'Europe',
    population: 5458827,
    latlng: [48.66666666, 19.5],
    demonym: 'Slovak',
    area: 49037,
    gini: 25,
    timezones: ['UTC+01:00'],
    borders: ['AUT', 'CZE', 'HUN', 'POL', 'UKR'],
    nativeName: 'Slovensko',
    numericCode: '703',
    flags: {
      svg: 'https://flagcdn.com/sk.svg',
      png: 'https://flagcdn.com/w320/sk.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'sk',
        iso639_2: 'slk',
        name: 'Slovak',
        nativeName: 'slovenčina',
      },
    ],
    translations: {
      br: 'Slovakia',
      pt: 'Eslováquia',
      nl: 'Slowakije',
      hr: 'Slovačka',
      fa: 'اسلواکی',
      de: 'Slowakei',
      es: 'República Eslovaca',
      fr: 'Slovaquie',
      ja: 'スロバキア',
      it: 'Slovacchia',
      hu: 'Szlovákia',
    },
    flag: 'https://flagcdn.com/sk.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'SVK',
    independent: true,
  },
  {
    name: 'Slovenia',
    topLevelDomain: ['.si'],
    alpha2Code: 'SI',
    alpha3Code: 'SVN',
    callingCodes: ['386'],
    capital: 'Ljubljana',
    altSpellings: ['SI', 'Republic of Slovenia', 'Republika Slovenija'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 2100126,
    latlng: [46.11666666, 14.81666666],
    demonym: 'Slovene',
    area: 20273,
    gini: 24.6,
    timezones: ['UTC+01:00'],
    borders: ['AUT', 'HRV', 'ITA', 'HUN'],
    nativeName: 'Slovenija',
    numericCode: '705',
    flags: {
      svg: 'https://flagcdn.com/si.svg',
      png: 'https://flagcdn.com/w320/si.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'sl',
        iso639_2: 'slv',
        name: 'Slovene',
        nativeName: 'slovenski jezik',
      },
    ],
    translations: {
      br: 'Slovenia',
      pt: 'Eslovénia',
      nl: 'Slovenië',
      hr: 'Slovenija',
      fa: 'اسلوونی',
      de: 'Slowenien',
      es: 'Eslovenia',
      fr: 'Slovénie',
      ja: 'スロベニア',
      it: 'Slovenia',
      hu: 'Szlovénia',
    },
    flag: 'https://flagcdn.com/si.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'SLO',
    independent: true,
  },
  {
    name: 'Spain',
    topLevelDomain: ['.es'],
    alpha2Code: 'ES',
    alpha3Code: 'ESP',
    callingCodes: ['34'],
    capital: 'Madrid',
    altSpellings: ['ES', 'Kingdom of Spain', 'Reino de España'],
    subregion: 'Southern Europe',
    region: 'Europe',
    population: 47351567,
    latlng: [40, -4],
    demonym: 'Spanish',
    area: 505992,
    gini: 34.7,
    timezones: ['UTC', 'UTC+01:00'],
    borders: ['AND', 'FRA', 'GIB', 'PRT', 'MAR'],
    nativeName: 'España',
    numericCode: '724',
    flags: {
      svg: 'https://flagcdn.com/es.svg',
      png: 'https://flagcdn.com/w320/es.png',
    },
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'es',
        iso639_2: 'spa',
        name: 'Spanish',
        nativeName: 'Español',
      },
    ],
    translations: {
      br: 'Spagn',
      pt: 'Espanha',
      nl: 'Spanje',
      hr: 'Španjolska',
      fa: 'اسپانیا',
      de: 'Spanien',
      es: 'España',
      fr: 'Espagne',
      ja: 'スペイン',
      it: 'Spagna',
      hu: 'Spanyolország',
    },
    flag: 'https://flagcdn.com/es.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'ESP',
    independent: true,
  },
  {
    name: 'Svalbard and Jan Mayen',
    topLevelDomain: ['.sj'],
    alpha2Code: 'SJ',
    alpha3Code: 'SJM',
    callingCodes: ['47'],
    capital: 'Longyearbyen',
    altSpellings: ['SJ', 'Svalbard and Jan Mayen Islands'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 2562,
    latlng: [78, 20],
    demonym: 'Norwegian',
    timezones: ['UTC+01:00'],
    nativeName: 'Svalbard og Jan Mayen',
    numericCode: '744',
    flags: {
      svg: 'https://flagcdn.com/sj.svg',
      png: 'https://flagcdn.com/w320/sj.png',
    },
    currencies: [
      {
        code: 'NOK',
        name: 'Norwegian krone',
        symbol: 'kr',
      },
    ],
    languages: [
      {
        iso639_1: 'no',
        iso639_2: 'nor',
        name: 'Norwegian',
        nativeName: 'Norsk',
      },
    ],
    translations: {
      br: 'Svalbard ha Jan Mayen',
      pt: 'Svalbard',
      nl: 'Svalbard en Jan Mayen',
      hr: 'Svalbard i Jan Mayen',
      fa: 'سوالبارد و یان ماین',
      de: 'Svalbard und Jan Mayen',
      es: 'Islas Svalbard y Jan Mayen',
      fr: 'Svalbard et Jan Mayen',
      ja: 'スヴァールバル諸島およびヤンマイエン島',
      it: 'Svalbard e Jan Mayen',
      hu: 'Spitzbergák és Jan Mayen-szigetek',
    },
    flag: 'https://flagcdn.com/sj.svg',
    independent: false,
  },
  {
    name: 'Sweden',
    topLevelDomain: ['.se'],
    alpha2Code: 'SE',
    alpha3Code: 'SWE',
    callingCodes: ['46'],
    capital: 'Stockholm',
    altSpellings: ['SE', 'Kingdom of Sweden', 'Konungariket Sverige'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 10353442,
    latlng: [62, 15],
    demonym: 'Swedish',
    area: 450295,
    gini: 30,
    timezones: ['UTC+01:00'],
    borders: ['FIN', 'NOR'],
    nativeName: 'Sverige',
    numericCode: '752',
    flags: {
      svg: 'https://flagcdn.com/se.svg',
      png: 'https://flagcdn.com/w320/se.png',
    },
    currencies: [
      {
        code: 'SEK',
        name: 'Swedish krona',
        symbol: 'kr',
      },
    ],
    languages: [
      {
        iso639_1: 'sv',
        iso639_2: 'swe',
        name: 'Swedish',
        nativeName: 'svenska',
      },
    ],
    translations: {
      br: 'Sveden',
      pt: 'Suécia',
      nl: 'Zweden',
      hr: 'Švedska',
      fa: 'سوئد',
      de: 'Schweden',
      es: 'Suecia',
      fr: 'Suède',
      ja: 'スウェーデン',
      it: 'Svezia',
      hu: 'Svédország',
    },
    flag: 'https://flagcdn.com/se.svg',
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'SWE',
    independent: true,
  },
  {
    name: 'Switzerland',
    topLevelDomain: ['.ch'],
    alpha2Code: 'CH',
    alpha3Code: 'CHE',
    callingCodes: ['41'],
    capital: 'Bern',
    altSpellings: [
      'CH',
      'Swiss Confederation',
      'Schweiz',
      'Suisse',
      'Svizzera',
      'Svizra',
    ],
    subregion: 'Central Europe',
    region: 'Europe',
    population: 8636896,
    latlng: [47, 8],
    demonym: 'Swiss',
    area: 41284,
    gini: 33.1,
    timezones: ['UTC+01:00'],
    borders: ['AUT', 'FRA', 'ITA', 'LIE', 'DEU'],
    nativeName: 'Schweiz',
    numericCode: '756',
    flags: {
      svg: 'https://flagcdn.com/ch.svg',
      png: 'https://flagcdn.com/w320/ch.png',
    },
    currencies: [
      {
        code: 'CHF',
        name: 'Swiss franc',
        symbol: 'Fr',
      },
    ],
    languages: [
      {
        iso639_1: 'de',
        iso639_2: 'deu',
        name: 'German',
        nativeName: 'Deutsch',
      },
      {
        iso639_1: 'fr',
        iso639_2: 'fra',
        name: 'French',
        nativeName: 'français',
      },
      {
        iso639_1: 'it',
        iso639_2: 'ita',
        name: 'Italian',
        nativeName: 'Italiano',
      },
      {
        iso639_2: 'roh',
        name: 'Romansh',
      },
    ],
    translations: {
      br: 'Suis',
      pt: 'Suíça',
      nl: 'Zwitserland',
      hr: 'Švicarska',
      fa: 'سوئیس',
      de: 'Schweiz',
      es: 'Suiza',
      fr: 'Suisse',
      ja: 'スイス',
      it: 'Svizzera',
      hu: 'Svájc',
    },
    flag: 'https://flagcdn.com/ch.svg',
    regionalBlocs: [
      {
        acronym: 'EFTA',
        name: 'European Free Trade Association',
      },
    ],
    cioc: 'SUI',
    independent: true,
  },
  {
    name: 'Ukraine',
    topLevelDomain: ['.ua'],
    alpha2Code: 'UA',
    alpha3Code: 'UKR',
    callingCodes: ['380'],
    capital: 'Kyiv',
    altSpellings: ['UA', 'Ukrayina'],
    subregion: 'Eastern Europe',
    region: 'Europe',
    population: 44134693,
    latlng: [49, 32],
    demonym: 'Ukrainian',
    area: 603700,
    gini: 26.6,
    timezones: ['UTC+02:00'],
    borders: ['BLR', 'HUN', 'MDA', 'POL', 'ROU', 'RUS', 'SVK'],
    nativeName: 'Україна',
    numericCode: '804',
    flags: {
      svg: 'https://flagcdn.com/ua.svg',
      png: 'https://flagcdn.com/w320/ua.png',
    },
    currencies: [
      {
        code: 'UAH',
        name: 'Ukrainian hryvnia',
        symbol: '₴',
      },
    ],
    languages: [
      {
        iso639_1: 'uk',
        iso639_2: 'ukr',
        name: 'Ukrainian',
        nativeName: 'Українська',
      },
    ],
    translations: {
      br: 'Ukraina',
      pt: 'Ucrânia',
      nl: 'Oekraïne',
      hr: 'Ukrajina',
      fa: 'وکراین',
      de: 'Ukraine',
      es: 'Ucrania',
      fr: 'Ukraine',
      ja: 'ウクライナ',
      it: 'Ucraina',
      hu: 'Ukrajna',
    },
    flag: 'https://flagcdn.com/ua.svg',
    cioc: 'UKR',
    independent: true,
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    topLevelDomain: ['.uk'],
    alpha2Code: 'GB',
    alpha3Code: 'GBR',
    callingCodes: ['44'],
    capital: 'London',
    altSpellings: ['GB', 'UK', 'Great Britain'],
    subregion: 'Northern Europe',
    region: 'Europe',
    population: 67215293,
    latlng: [54, -2],
    demonym: 'British',
    area: 242900,
    gini: 35.1,
    timezones: [
      'UTC-08:00',
      'UTC-05:00',
      'UTC-04:00',
      'UTC-03:00',
      'UTC-02:00',
      'UTC',
      'UTC+01:00',
      'UTC+02:00',
      'UTC+06:00',
    ],
    borders: ['IRL'],
    nativeName: 'United Kingdom',
    numericCode: '826',
    flags: {
      svg: 'https://flagcdn.com/gb.svg',
      png: 'https://flagcdn.com/w320/gb.png',
    },
    currencies: [
      {
        code: 'GBP',
        name: 'British pound',
        symbol: '£',
      },
    ],
    languages: [
      {
        iso639_1: 'en',
        iso639_2: 'eng',
        name: 'English',
        nativeName: 'English',
      },
    ],
    translations: {
      br: 'Rouantelezh-Unanet',
      pt: 'Reino Unido',
      nl: 'Verenigd Koninkrijk',
      hr: 'Ujedinjeno Kraljevstvo',
      fa: 'بریتانیای کبیر و ایرلند شمالی',
      de: 'Vereinigtes Königreich',
      es: 'Reino Unido',
      fr: 'Royaume-Uni',
      ja: 'イギリス',
      it: 'Regno Unito',
      hu: 'Nagy-Britannia',
    },
    flag: 'https://flagcdn.com/gb.svg',
    cioc: 'GBR',
    independent: true,
  },
] as unknown as ICountry[];
